services:

  database:
    image: postgres:16.6
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=lportal
    volumes:
       - ./database-dump/:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  liferay:
    image: liferay/dxp:2025.q1.7-lts
    environment:
      - LIFERAY_JVM_OPTS=-Xms3g -Xmx4g
      - LIFERAY_JPDA_ENABLED=true
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_DRIVER_UPPERCASEC_LASS_UPPERCASEN_AME=org.postgresql.Driver
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_URL=jdbc:postgresql://database:5432/lportal?characterEncoding=utf8&dontTrackOpenResources=true&holdResultsOpenOverStatementClose=true&serverTimezone=GMT&useFastDateParsing=false&useUnicode=true
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_USERNAME=root
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_PASSWORD=root
      - LIFERAY_MODULE_PERIOD_FRAMEWORK_PERIOD_PROPERTIES_PERIOD_OSGI_PERIOD_CONSOLE=0.0.0.0:11311
      - LIFERAY_RETRY_PERIOD_JDBC_PERIOD_ON_PERIOD_STARTUP_PERIOD_DELAY=20
      - LIFERAY_RETRY_PERIOD_JDBC_PERIOD_ON_PERIOD_STARTUP_PERIOD_MAX_PERIOD_RETRIES=5
    ports:
      - "8080:8080"
      - "11311:11311"
      - "8000:8000"
    volumes:
      - ./liferay-files:/mnt/liferay/files
      - ./liferay-deploy:/mnt/liferay/deploy
      - ./liferay-document-library:/opt/liferay/data/document_library
    depends_on:
      - database
      - search

  search:
    image: baseline/elasticsearch
    build: ./elasticsearch/
    environment:
      - cluster.name=LiferayElasticsearchCluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
      - "node.name=es-node1"
      - "xpack.security.enabled=false"
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data

  webserver:
    image: baseline/nginx
    build: ./docker-compose/webserver/
    ports:
      - "80:80"
    depends_on:
      - liferay