{
 "title": "JVM overview - Prometheus",
 "description": "Dashboard for JVM metrics with Prometheus / JMX Exporter",
 "tags": [
  "JVM",
  "prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "title": "CPU load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "jvm_cpu_systemcpuload{job=\"liferay-jvm\"}",
     "legendFormat": "System Load"
    },
    {
     "expr": "jvm_cpu_processcpuload{job=\"liferay-jvm\"}",
     "legendFormat": "Process Load"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{area}} memory [{{instance}}]"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_current{instance=~\"$instance\"}",
     "legendFormat": "current [{{instance}}]"
    },
    {
     "expr": "jvm_threads_daemon{instance=~\"$instance\"}",
     "legendFormat": "daemon [{{instance}}]"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_classes_currently_loaded{instance=~\"$instance\"}",
     "legendFormat": "loaded [{{instance}}]"
    }
   ]
  },
  {
   "title": "GC time / 1 min. rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{instance=~\"$instance\"}[1m])",
     "legendFormat": "{{gc}} [{{instance}}]"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{instance=~\"$instance\"}",
     "legendFormat": "{{gc}} [{{instance}}]"
    }
   ]
  }
 ]
}