apiVersion: 1

datasources:
  - name: MyInfluxDB
    type: influxdb
    url: http://influxdb:8086
    isDefault: true
    user: admin
    secureJsonData:
      password: admin123
    jsonData:
      dbName: mydb
  
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
